### ISSUE TITLE
cart data

### ISSUE THREAD

**Issue by Mpese-Joao** [RIP21/bigcommerce-fetch#1]
I want to kno if it is possible to access the cart data through the App?
I'm asking because i'm developing an app to read cart data. But whenever a press the button i get 401 error:

const fetchBigCommerceData = async () => {
try {
const response = await fetch(
"[https://api.bigcommerce.com/stores/aherf0o3nw/v3/carts/{CartId}](https://api.bigcommerce.com/stores/aherf0o3nw/v3/carts/%7BCartId%7D)",
{
headers: {
"Accept" : "application/json",
"Content-Type" : "application/json",
"X-Auth-Token" : "4*****************************,
"X-Auth-Client" : "a*****************************",
},
mode: "no-cors",
}
);

**Comment by RIP21** [comment]
To be honest I haven't touched Bigcommerce for like 7 years already and have never been an expert. It was one-off task I did :) 

If the above is the code as is, then you need to replace `CartId` with the actual cart id. And `401` basically tells that you're not authorized https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/401 so you're probably authenticated, it's just not enough permissions to authorize this request. Otherwise, it would be `403`. 

Aaanyway, it's not free consulting here :D So I won't dig into this any longer :) Good luck :)
